---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ups-broker
  labels:
    app: ups-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ups-broker
  template:
    metadata:
      labels:
        app: ups-broker
    spec:
      containers:
      - name: ups-broker
        image: quay.io/kubernetes-service-catalog/user-broker:v0.1.14
        imagePullPolicy: Always
        args:
        - --port
        - "8080"
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
