---
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-config
  namespace: broker
  labels:
    app: ansible-service-broker
data:
  broker-config: |
    registry:
      - type: "dockerhub"
        name: "dh"
        url: "https://registry.hub.docker.com"
        org: "ansibleplaybookbundle"
        tag: "latest"
        white_list:
          - ".*-apb$"
    dao:
      type: "crd"
    log:
      logfile: /var/log/ansible-service-broker/asb.log
      stdout: true
      level: debug
      color: true
    openshift:
      host: ""
      ca_file: ""
      bearer_token_file: ""
      image_pull_policy: "IfNotPresent"
      sandbox_role: "edit"
      namespace: broker
      keep_namespace: false
      keep_namespace_on_error: true
    broker:
      dev_broker: true
      bootstrap_on_startup: true
      refresh_interval: "600s"
      launch_apb_on_bind: false
      output_request: true
      recovery: true
      ssl_cert_key: /etc/tls/private/tls.key
      ssl_cert: /etc/tls/private/tls.crt
      auto_escalate: true
      auth:
        - type: basic
          enabled: false
