---
apiVersion: v1
kind: Secret
metadata:
  name: asb-auth-secret
  namespace: broker
data:
  username: "YWRtaW4="
  password: "YWRtaW4="

---
apiVersion: v1
kind: Secret
metadata:
  name: ansibleservicebroker-client
  namespace: broker
  annotations:
    kubernetes.io/service-account.name: ansibleservicebroker-client
type: kubernetes.io/service-account-token
