---
apiVersion: v1
kind: Service
metadata:
   name: asb
   namespace: broker
   labels:
     app: ansible-service-broker
     service: asb
spec:
  ports:
    - name: port-1338
      port: 1338
      targetPort: 1338
      protocol: TCP
  selector:
    app: ansible-service-broker
    service: asb
