---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: catalog-controller-manager
  namespace: catalog
  labels:
    app: catalog-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-controller-manager
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: catalog-controller-manager
    spec:
      serviceAccountName: "service-catalog-controller-manager"
      containers:
      - name: controller-manager
        image: quay.io/kubernetes-service-catalog/service-catalog:v0.1.14
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
        env:
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
        - controller-manager
        - --secure-port
        - "8444"
        - "--leader-elect=false"
        - -v
        - "10"
        - --resync-interval
        - 5m
        - --broker-relist-interval
        - 24h
        ports:
        - containerPort: 8444
        volumeMounts:
        - name: service-catalog-cert
          mountPath: /var/run/kubernetes-service-catalog
          readOnly: true
        readinessProbe:
          httpGet:
            port: 8444
            path: /healthz
            scheme: HTTPS
          failureThreshold: 1
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            port: 8444
            path: /healthz
            scheme: HTTPS
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
      volumes:
      - name: service-catalog-cert
        secret:
          secretName: catalog-apiserver-cert
          items:
          - key: tls.crt
            path: apiserver.crt
          - key: tls.key
            path: apiserver.key
