---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: "service-catalog-apiserver"
      namespace: catalog
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: "service-catalog-controller-manager"
      namespace: catalog
